version: "3.2"

services:
  publisher:
    image: publisher
    build:
      context: ./publisher
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      rabbitmq:
        condition: service_healthy
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672 # RabbitMQ-standaardpoort voor AMQP
        - 15672:15672 # RabbitMQ management GUI-poort
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERMAME} 
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD} 
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      timeout: 20s
  subscriber:
    build: ./Subscriber
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - 9001:9001
  eurocard:
   build: ./eurocard
   depends_on:
    rabbitmq:
      condition: service_healthy
   ports: 
   - 5000:5000
  abonneeregistratie:
    build: ./AbonneeRegistratie
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports: 
    - 8080:8080
  rpc_server:
    build: ./rpc_server
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports: 
    - 8081:8081
networks:
  default:
    driver: bridge