#
# Build stage
#
FROM maven:3.6.0-jdk-11-slim AS build
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml clean package

#
# Package stage
#
FROM openjdk:11-jre-slim
ADD target/publisher.jar publisher.jar
ENTRYPOINT ["java", "-jar","publisher.jar"]
EXPOSE 9000
